# Generated by Django 4.2.27 on 2026-01-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0008_rename_amount_paid_parkingsession_final_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='guest_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
