# Generated by Django 4.2.27 on 2026-01-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0012_parkingsession_booking_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, help_text='INSECURE: Stores password in plain text for admin visibility', max_length=255, null=True),
        ),
    ]
