# Generated by Django 6.0.1 on 2026-02-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_analytics_api', '0005_delete_vehicleanalytics'),
        ('backend_core_api', '0014_add_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='session',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='session',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='shiftlog',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending_payment', 'Pending Payment')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='zone',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='BookingActivityLog',
        ),
        migrations.DeleteModel(
            name='Dispute',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ShiftLog',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
