# Generated by Django 6.0.1 on 2026-02-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_analytics_api', '0007_delete_vehicleanalytics'),
        ('backend_core_api', '0016_bookingactivitylog_dispute_feedback_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='session',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='session',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='shiftlog',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookingActivityLog',
        ),
        migrations.DeleteModel(
            name='Dispute',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ShiftLog',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
