# Generated by Django 4.2.27 on 2026-01-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_analytics_api', '0002_staffsalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('success', 'Success'), ('info', 'Info')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
