# Generated by Django 4.2.27 on 2026-01-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_analytics_api', '0003_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffSalary',
        ),
    ]
