# Generated by Django 6.0.1 on 2026-02-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_analytics_api', '0004_delete_staffsalary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleAnalytics',
        ),
    ]
