# Generated by Django 6.0.1 on 2026-02-03 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_analytics_api', '0005_delete_vehicleanalytics'),
        ('backend_core_api', '0016_bookingactivitylog_dispute_feedback_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_core_api.zone')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='backend_core_api.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Analytics',
                'verbose_name_plural': 'Vehicle Analytics',
            },
        ),
    ]
