# Generated by Django 6.0.1 on 2026-02-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_analytics_api', '0006_vehicleanalytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleAnalytics',
        ),
    ]
