import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// API configuration
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ? `${import.meta.env.VITE_API_BASE_URL}/api` : 'http://localhost:8000/api';

const reportApi = {
  getDailyShift: (date) =>
    fetch(`${API_BASE_URL}/core/shift-logs/?date=${date}`)
      .then(res => res.json()),

  getRevenueSummary: () =>
    fetch(`${API_BASE_URL}/analytics/revenue/`)
      .then(res => res.json()),

  getVehicleHistory: (vehicleNumber) =>
    fetch(`${API_BASE_URL}/core/sessions/?vehicle_number=${vehicleNumber}`)
      .then(res => res.json()),

  getZonePerformance: () =>
    fetch(`${API_BASE_URL}/analytics/zones/`)
      .then(res => res.json())
};

const Reports = () => {
  const [selectedReport, setSelectedReport] = useState('daily');
  const [showHistoryModal, setShowHistoryModal] = useState(false);
  const [showResultsModal, setShowResultsModal] = useState(false);
  const [vehicleInput, setVehicleInput] = useState('');
  const [historyResults, setHistoryResults] = useState([]);

  // ... (previous functions remain the same) ...

  const exportReports = async () => {
    try {
      const doc = new jsPDF();
      const date = new Date().toLocaleDateString();
      const isoDate = new Date().toISOString().split('T')[0];

      // Header
      doc.setFontSize(20);
      doc.setTextColor(40, 44, 52);
      doc.text("Quick Park Management System", 14, 20);

      doc.setFontSize(14);
      doc.setTextColor(100);
      doc.text(`Daily Report - ${date}`, 14, 30);
      doc.setLineWidth(0.5);
      doc.line(14, 32, 196, 32);

      // Section 1: Daily Shift Summary
      doc.setFontSize(16);
      doc.setTextColor(0);
      doc.text("1. Shift Summary", 14, 45);

      const shiftResponse = await reportApi.getDailyShift(isoDate);
      let shiftData = null;

      if (Array.isArray(shiftResponse)) {
        shiftData = shiftResponse[0];
      } else if (shiftResponse.results && shiftResponse.results.length > 0) {
        shiftData = shiftResponse.results[0];
      } else if (shiftResponse.success && shiftResponse.data) {
        shiftData = shiftResponse.data;
      }

      if (!shiftData) {
        try {
          const dRes = await fetch(`${API_BASE_URL}/analytics/dashboard/`).then(r => r.json());
          if (dRes.success) {
            shiftData = {
              staff_name: dRes.data.current_staff_name,
              entry_count: dRes.data.vehicles_entered,
              exit_count: dRes.data.completed_sessions,
              revenue_collected: dRes.data.total_revenue,
              cash_revenue: dRes.data.cash_revenue,
              online_revenue: dRes.data.online_revenue
            };
          }
        } catch (e) { }
      }

      const finalShiftData = shiftData || { staff_name: 'N/A', entry_count: 0, exit_count: 0 };

      autoTable(doc, {
        startY: 50,
        head: [['Metric', 'Value']],
        body: [
          ['Current Staff', finalShiftData.staff_name || 'N/A'],
          ['Entries Processed', (finalShiftData.entry_count || 0).toString()],
          ['Exits Processed', (finalShiftData.exit_count || 0).toString()],
          ['Total Vehicles', ((finalShiftData.entry_count || 0) + (finalShiftData.exit_count || 0)).toString()]
        ],
        theme: 'grid',
        headStyles: { fillColor: [63, 81, 181] }
      });

      // Section 2: Revenue Collection
      let currentY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 120;
      doc.text("2. Revenue Collection", 14, currentY);

      const revResponse = await reportApi.getRevenueSummary();
      let revData = { cash_revenue: 0, online_revenue: 0, total_revenue: 0 };
      if (revResponse.data) {
        revData = revResponse.data;
      } else if (revResponse.success && !revResponse.data) {
        // logic error in backend?
      } else {
        revData = revResponse;
      }

      autoTable(doc, {
        startY: currentY + 5,
        head: [['Payment Method', 'Amount']],
        body: [
          ['Cash', `Rs. ${revData.cash_revenue || 0}`],
          ['Online', `Rs. ${revData.online_revenue || 0}`],
          ['Total Revenue', `Rs. ${revData.total_revenue || 0}`]
        ],
        theme: 'striped',
        headStyles: { fillColor: [46, 125, 50] }
      });

      // Footer
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text("Generated by Quick Park System", 14, 280);
      doc.text(new Date().toLocaleString(), 14, 285);

      doc.save(`Daily_Report_${isoDate}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert(`Failed to generate PDF report: ${error.message || 'Check console for details'}`);
    }
  };


  const viewDailyShiftReport = async () => {
    try {
      const date = new Date().toISOString().split('T')[0];
      const response = await reportApi.getDailyShift(date);
      console.log('Shift API Response:', response); // Debug log

      let data;
      if (Array.isArray(response)) {
        data = response[0];
      } else if (response.results && response.results.length > 0) {
        data = response.results[0];
      } else if (response.success && response.data) {
        data = response.data;
      }

      if (!data) {
        // Fallback: Try to get data from dashboard stats if no shift log exists
        try {
          const dashboardRes = await fetch(`${API_BASE_URL}/analytics/dashboard/`).then(r => r.json());
          if (dashboardRes.success) {
            data = {
              staff_name: dashboardRes.data.current_staff_name,
              entry_count: dashboardRes.data.vehicles_entered,
              exit_count: dashboardRes.data.completed_sessions,
              revenue_collected: dashboardRes.data.total_revenue,
              cash_collected: dashboardRes.data.cash_revenue,
              online_collected: dashboardRes.data.online_revenue
            };
          } else {
            throw new Error('Dashboard fetch failed');
          }
        } catch (e) {
          data = {
            staff_name: 'No Active Shift',
            entry_count: 0,
            exit_count: 0,
            revenue_collected: 0,
            cash_collected: 0,
            online_collected: 0
          };
        }
      }

      const popup = window.open('', '_blank', 'width=900,height=700');
      popup.document.write(`
        <html>
          <head><title>Daily Shift Report</title></head>
          <body style="font-family: Arial, sans-serif; padding: 20px; background: #f1f5f9;">
            <div style="background: white; border-radius: 12px; padding: 30px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
              <h2 style="color: #1e293b; margin-bottom: 20px; font-size: 24px; font-weight: 600;">📋 Daily Shift Report - ${new Date().toLocaleDateString()}</h2>
              <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px;">
                <div style="background: #f8fafc; padding: 15px; border-radius: 8px;">
                  <h3 style="color: #374151; margin: 0 0 10px 0;">Shift Summary</h3>
                  <p style="margin: 5px 0; color: #6b7280;">• Date: ${date}</p>
                  <p style="margin: 5px 0; color: #6b7280;">• Staff Member: ${data.staff_name}</p>
                </div>
                <div style="background: #f8fafc; padding: 15px; border-radius: 8px;">
                  <h3 style="color: #374151; margin: 0 0 10px 0;">Vehicle Statistics</h3>
                  <p style="margin: 5px 0; color: #6b7280;">• Entries Processed: ${data.entry_count}</p>
                  <p style="margin: 5px 0; color: #6b7280;">• Exits Processed: ${data.exit_count}</p>
                  <p style="margin: 5px 0; color: #6b7280;">• Total: ${data.entry_count + data.exit_count}</p>
                </div>
              </div>
              <div style="background: #f8fafc; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
                <h3 style="color: #374151; margin: 0 0 10px 0;">Revenue Collection</h3>
                <p style="margin: 5px 0; color: #6b7280;">• Total Collection: ₹${data.revenue_collected}</p>
                <p style="margin: 5px 0; color: #6b7280;">• Cash: ₹${data.cash_collected}</p>
                <p style="margin: 5px 0; color: #6b7280;">• Online: ₹${data.online_collected}</p>
              </div>
              <button onclick="window.print()" style="background: #3b82f6; color: white; padding: 10px 20px; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 600; margin-right: 10px;">Print Report</button>
              <button onclick="window.close()" style="background: #6b7280; color: white; padding: 10px 20px; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 600;">Close</button>
            </div>
          </body>
        </html>
      `);
    } catch (error) {
      console.error('Error fetching shift report:', error);
      alert('Failed to load report data');
    }
  };

  const viewPaymentSummary = async () => {
    try {
      const response = await reportApi.getRevenueSummary();
      console.log('Payment API Response:', response); // Debug log

      // Handle different response structures
      let data;
      if (response.success && response.data) {
        data = response.data;
      } else if (response.data) {
        data = response.data;
      } else {
        // Fallback with mock data
        data = { cash_revenue: 0, online_revenue: 0, total_revenue: 0 };
      }

      const cashPercent = data.total_revenue > 0 ? Math.round((data.cash_revenue / data.total_revenue) * 100) : 0;
      const onlinePercent = data.total_revenue > 0 ? Math.round((data.online_revenue / data.total_revenue) * 100) : 0;

      const popup = window.open('', '_blank', 'width=800,height=600');
      popup.document.write(`
        <html>
          <head><title>Payment Summary</title></head>
          <body style="font-family: Arial, sans-serif; padding: 20px; background: #f1f5f9;">
            <div style="background: white; border-radius: 12px; padding: 30px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
              <h2 style="color: #1e293b; margin-bottom: 20px; font-size: 24px; font-weight: 600;">💳 Payment Summary</h2>
              <div style="overflow-x: auto;">
                <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
                  <thead>
                    <tr style="background: #f8fafc;">
                      <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e2e8f0;">Payment Method</th>
                      <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e2e8f0;">Amount</th>
                      <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e2e8f0;">Percentage</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">Cash</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">₹${data.cash_revenue}</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">${cashPercent}%</td>
                    </tr>
                    <tr>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">Online (UPI/Card)</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">₹${data.online_revenue}</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">${onlinePercent}%</td>
                    </tr>
                    <tr style="background: #f0fdf4; font-weight: bold;">
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">Total</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">₹${data.total_revenue}</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">100%</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <button onclick="window.close()" style="background: #3b82f6; color: white; padding: 10px 20px; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 600;">Close</button>
            </div>
          </body>
        </html>
      `);
    } catch (error) {
      console.error('Error fetching payment summary:', error);

      // Show popup with mock data when API fails
      const data = { cash_revenue: 1500, online_revenue: 2500, total_revenue: 4000 };
      const cashPercent = 38;
      const onlinePercent = 62;

      const popup = window.open('', '_blank', 'width=800,height=600');
      popup.document.write(`
        <html>
          <head><title>Payment Summary</title></head>
          <body style="font-family: Arial, sans-serif; padding: 20px; background: #f1f5f9;">
            <div style="background: white; border-radius: 12px; padding: 30px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
              <h2 style="color: #1e293b; margin-bottom: 20px; font-size: 24px; font-weight: 600;">💳 Payment Summary</h2>
              <div style="background: #fef3c7; padding: 15px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #f59e0b;">
                <p style="margin: 0; color: #92400e; font-weight: 600;">⚠️ Using sample data - Backend connection failed</p>
              </div>
              <div style="overflow-x: auto;">
                <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
                  <thead>
                    <tr style="background: #f8fafc;">
                      <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e2e8f0;">Payment Method</th>
                      <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e2e8f0;">Amount</th>
                      <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e2e8f0;">Percentage</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">Cash</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">₹${data.cash_revenue}</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">${cashPercent}%</td>
                    </tr>
                    <tr>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">Online (UPI/Card)</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">₹${data.online_revenue}</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">${onlinePercent}%</td>
                    </tr>
                    <tr style="background: #f0fdf4; font-weight: bold;">
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">Total</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">₹${data.total_revenue}</td>
                      <td style="padding: 12px; border-bottom: 1px solid #e2e8f0;">100%</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <button onclick="window.close()" style="background: #3b82f6; color: white; padding: 10px 20px; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 600;">Close</button>
            </div>
          </body>
        </html>
      `);
    }
  };

  const handleSearchHistory = async () => {
    if (!vehicleInput) return;

    try {
      const response = await reportApi.getVehicleHistory(vehicleInput);
      const sessions = response.sessions || [];
      setHistoryResults(sessions);
      setShowHistoryModal(false);
      setShowResultsModal(true);
    } catch (error) {
      console.error('Error fetching vehicle history:', error);
      alert('Failed to load vehicle history');
    }
  };

  const viewZonePerformance = async () => {
    try {
      const response = await reportApi.getZonePerformance();
      const zones = response.data || [];

      let zoneCards = '';
      zones.forEach(zone => {
        zoneCards += `
          <div style="background: #f8fafc; padding: 15px; border-radius: 8px;">
            <h3 style="color: #374151; margin: 0 0 10px 0;">${zone.zone_name}</h3>
            <p style="margin: 5px 0; color: #6b7280;">• Occupancy: ${Math.round(zone.occupancy_rate)}%</p>
            <p style="margin: 5px 0; color: #6b7280;">• Slots: ${zone.available_slots} / ${zone.total_slots} Free</p>
            <p style="margin: 5px 0; color: #6b7280;">• Active: ${zone.active_sessions}</p>
          </div>
        `;
      });

      const popup = window.open('', '_blank', 'width=800,height=600');
      popup.document.write(`
        <html>
          <head><title>Zone Performance</title></head>
          <body style="font-family: Arial, sans-serif; padding: 20px; background: #f1f5f9;">
            <div style="background: white; border-radius: 12px; padding: 30px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
              <h2 style="color: #1e293b; margin-bottom: 20px; font-size: 24px; font-weight: 600;">🏢 Zone Performance</h2>
              <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-bottom: 20px;">
                ${zoneCards || '<p>No data available</p>'}
              </div>
              <button onclick="window.close()" style="background: #3b82f6; color: white; padding: 10px 20px; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 600;">Close</button>
            </div>
          </body>
        </html>
      `);
    } catch (error) {
      console.error('Error fetching zone performance:', error);
      alert('Failed to load zone data');
    }
  };

  const viewStaffEfficiency = () => {
    alert('Staff efficiency logic needs backend ShiftLog aggregation');
  };



  return (
    <div className="reports">
      <div className="reports-header">
        <div className="header-content">
          <div className="logo-section">
            <div className="system-logo">🅿️</div>
            <div className="system-info">
              <h2>Quick Park</h2>
              <p>Management System</p>
            </div>
          </div>
          <h1>📈 Reports</h1>
        </div>
      </div>

      <div className="reports-content">
        <div className="report-categories">
          <div className="report-card" onClick={viewDailyShiftReport}>
            <h3>📋 Daily Shift Report</h3>
            <p>Complete shift summary with statistics</p>
          </div>

          <div className="report-card" onClick={viewPaymentSummary}>
            <h3>💳 Payment Summary</h3>
            <p>Payment methods and collection details</p>
          </div>

          <div className="report-card" onClick={() => setShowHistoryModal(true)}>
            <h3>🚗 Vehicle History</h3>
            <p>Complete vehicle entry/exit records</p>
          </div>

          <div className="report-card" onClick={viewZonePerformance}>
            <h3>🏢 Zone Performance</h3>
            <p>Zone-wise occupancy and revenue</p>
          </div>

          <div className="report-card" onClick={viewStaffEfficiency}>
            <h3>👨‍💼 Staff Efficiency</h3>
            <p>Performance metrics and ratings</p>
          </div>

          <div className="report-card export-card" onClick={exportReports}>
            <h3>📤 Export Reports</h3>
            <p>Download reports in PDF format</p>
          </div>
        </div>
      </div>

      {showHistoryModal && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: 'rgba(0,0,0,0.5)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 1000,
          backdropFilter: 'blur(5px)'
        }}>
          <div style={{
            background: 'white',
            padding: '30px',
            borderRadius: '16px',
            width: '100%',
            maxWidth: '400px',
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)'
          }}>
            <h3 style={{ margin: '0 0 20px 0', color: '#1e293b', fontSize: '1.5rem' }}>Search Vehicle History</h3>

            <div className="form-group" style={{ marginBottom: '25px' }}>
              <label style={{ display: 'block', marginBottom: '8px', fontWeight: 'bold', color: '#475569' }}>Vehicle Number</label>
              <input
                type="text"
                value={vehicleInput}
                onChange={(e) => setVehicleInput(e.target.value.toUpperCase())}
                placeholder="Enter vehicle number (e.g. MH12AB1234)"
                style={{
                  width: '100%',
                  padding: '12px',
                  border: '2px solid #e2e8f0',
                  borderRadius: '8px',
                  fontSize: '1rem',
                  outline: 'none',
                  transition: 'border-color 0.2s'
                }}
                onFocus={(e) => e.target.style.borderColor = '#3b82f6'}
                onBlur={(e) => e.target.style.borderColor = '#e2e8f0'}
                onKeyDown={(e) => e.key === 'Enter' && handleSearchHistory()}
                autoFocus
              />
            </div>

            <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
              <button
                onClick={() => { setShowHistoryModal(false); setVehicleInput(''); }}
                style={{
                  padding: '10px 20px',
                  border: '1px solid #cbd5e1',
                  background: 'white',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  fontWeight: '600',
                  color: '#64748b'
                }}
              >
                Cancel
              </button>
              <button
                onClick={handleSearchHistory}
                style={{
                  padding: '10px 20px',
                  border: 'none',
                  background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
                  color: 'white',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  fontWeight: '600',
                  boxShadow: '0 4px 6px -1px rgba(37, 99, 235, 0.2)'
                }}
              >
                Search Record
              </button>
            </div>
          </div>
        </div>
      )}

      {showResultsModal && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: 'rgba(0,0,0,0.5)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 1000,
          backdropFilter: 'blur(5px)'
        }}>
          <div style={{
            background: 'white',
            padding: '30px',
            borderRadius: '16px',
            width: '90%',
            maxWidth: '1000px',
            maxHeight: '90vh',
            overflowY: 'auto',
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <div>
                <h3 style={{ margin: 0, color: '#1e293b', fontSize: '1.5rem' }}>Vehicle History</h3>
                <p style={{ margin: '5px 0 0 0', color: '#64748b' }}>Records for: <span style={{ fontWeight: 'bold', color: '#1e293b' }}>{vehicleInput || 'Unknown'}</span></p>
              </div>
              <button
                onClick={() => setShowResultsModal(false)}
                style={{ background: 'none', border: 'none', fontSize: '1.5rem', cursor: 'pointer', color: '#64748b' }}
              >
                ×
              </button>
            </div>

            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
                <thead>
                  <tr style={{ borderBottom: '2px solid #e2e8f0' }}>
                    <th style={{ padding: '12px', color: '#64748b', fontSize: '0.875rem' }}>Status</th>
                    <th style={{ padding: '12px', color: '#64748b', fontSize: '0.875rem' }}>Zone / Slot</th>
                    <th style={{ padding: '12px', color: '#64748b', fontSize: '0.875rem' }}>Entry Time</th>
                    <th style={{ padding: '12px', color: '#64748b', fontSize: '0.875rem' }}>Exit Time</th>
                    <th style={{ padding: '12px', color: '#64748b', fontSize: '0.875rem' }}>Duration</th>
                    <th style={{ padding: '12px', color: '#64748b', fontSize: '0.875rem' }}>Payment</th>
                    <th style={{ padding: '12px', color: '#64748b', fontSize: '0.875rem' }}>Amounts</th>
                  </tr>
                </thead>
                <tbody>
                  {historyResults.length > 0 ? (
                    historyResults.map((session) => (
                      <tr key={session.id} style={{ borderBottom: '1px solid #f1f5f9' }}>
                        <td style={{ padding: '12px' }}>
                          <span style={{
                            padding: '4px 8px',
                            borderRadius: '4px',
                            fontSize: '0.75rem',
                            fontWeight: '600',
                            backgroundColor: session.status === 'active' ? '#e0f2fe' : '#dcfce7',
                            color: session.status === 'active' ? '#0369a1' : '#15803d'
                          }}>
                            {session.status.toUpperCase()}
                          </span>
                        </td>
                        <td style={{ padding: '12px', fontWeight: '500', color: '#334155' }}>
                          {session.zone_name}<br />
                          <span style={{ fontSize: '0.8rem', color: '#94a3b8' }}>Slot: {session.slot_number || '-'}</span>
                        </td>
                        <td style={{ padding: '12px', fontSize: '0.9rem', color: '#475569' }}>
                          {new Date(session.entry_time).toLocaleString()}
                        </td>
                        <td style={{ padding: '12px', fontSize: '0.9rem', color: '#475569' }}>
                          {session.exit_time ? new Date(session.exit_time).toLocaleString() : '-'}
                        </td>
                        <td style={{ padding: '12px', fontSize: '0.9rem', color: '#475569' }}>
                          {session.duration || '-'}
                        </td>
                        <td style={{ padding: '12px', fontSize: '0.9rem', color: '#475569' }}>
                          <span style={{ display: 'block' }}>{session.payment_method || '-'}</span>
                          <span style={{ fontSize: '0.8rem', color: session.payment_status === 'paid' ? '#16a34a' : '#ea580c' }}>
                            {session.payment_status}
                          </span>
                        </td>
                        <td style={{ padding: '12px', fontWeight: '500', color: '#334155' }}>
                          <div>Total: ₹{session.total_amount_paid}</div>
                          <div style={{ fontSize: '0.8rem', color: '#94a3b8' }}>Init: ₹{session.initial_amount_paid}</div>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colspan="7" style={{ padding: '30px', textAlign: 'center', color: '#64748b' }}>
                        No records found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>

            <div style={{ marginTop: '30px', display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
              <button
                onClick={() => window.print()}
                style={{
                  padding: '10px 20px',
                  border: '1px solid #cbd5e1',
                  background: 'white',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  fontWeight: '600',
                  color: '#64748b'
                }}
              >
                🖨️ Print
              </button>
              <button
                onClick={() => setShowResultsModal(false)}
                style={{
                  padding: '10px 20px',
                  border: 'none',
                  background: '#3b82f6',
                  color: 'white',
                  borderRadius: '8px',
                  cursor: 'pointer',
                  fontWeight: '600'
                }}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
export default Reports;
