# Generated by Django 4.2.27 on 2026-01-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0002_vehicle_schedule_dispute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffSalary',
        ),
    ]
