# Generated by Django 4.2.27 on 2026-01-22 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0003_delete_staffsalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='backend_core_api.zone')),
            ],
            options={
                'ordering': ['zone', 'slot_number'],
                'unique_together': {('zone', 'slot_number')},
            },
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_core_api.slot'),
        ),
    ]
