# Generated by Django 4.2.27 on 2026-01-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0004_slot_parkingsession_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='dispute_type',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='dispute',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift_type',
            field=models.CharField(choices=[('Alpha', 'Alpha (06:00 - 14:00)'), ('Bravo', 'Bravo (14:00 - 22:00)'), ('Charlie', 'Charlie (22:00 - 06:00)')], default='Alpha', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
