# Generated by Django 4.2.27 on 2026-01-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0006_shiftlog_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftlog',
            old_name='vehicles_processed',
            new_name='entry_count',
        ),
        migrations.AddField(
            model_name='shiftlog',
            name='cash_collected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shiftlog',
            name='exit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftlog',
            name='online_collected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
