# Generated by Django 4.2.27 on 2026-01-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0007_rename_vehicles_processed_shiftlog_entry_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingsession',
            old_name='amount_paid',
            new_name='final_amount_paid',
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='initial_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Booking Fee'), ('FINAL', 'Final Exit Billing'), ('FULL', 'Full Pre-payment')], default='FULL', max_length=10),
        ),
    ]
