# Generated by Django 4.2.27 on 2026-01-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0009_parkingsession_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=15),
        ),
    ]
