# Generated by Django 4.2.27 on 2026-01-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0010_slot_is_reserved_alter_parkingsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='backend_core_api.zone'),
        ),
    ]
