# Generated by Django 4.2.27 on 2026-01-26 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_core_api', '0011_schedule_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='booking_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='cancellation_type',
            field=models.CharField(blank=True, choices=[('user_initiated', 'User Initiated'), ('auto_cancelled', 'Auto Cancelled'), ('admin_cancelled', 'Admin Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='extension_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='sms_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookingActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_cancelled', 'Booking Cancelled'), ('booking_extended', 'Booking Extended'), ('auto_cancelled', 'Auto Cancelled'), ('sms_sent', 'SMS Notification Sent'), ('refund_processed', 'Refund Processed')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='backend_core_api.parkingsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Activity Log',
                'verbose_name_plural': 'Booking Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
