# Generated by Django 4.2.27 on 2026-01-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_core_api', '0002_vehicle_schedule_dispute'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_duration', models.DurationField(blank=True, null=True)),
                ('peak_hour', models.TimeField(blank=True, null=True)),
                ('occupancy_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sessions', models.IntegerField(default=0)),
                ('cash_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Revenue Report',
                'verbose_name_plural': 'Revenue Reports',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_core_api.zone')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='backend_core_api.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Analytics',
                'verbose_name_plural': 'Vehicle Analytics',
            },
        ),
        migrations.CreateModel(
            name='PeakHourAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('sessions_count', models.IntegerField(default=0)),
                ('occupancy_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Peak Hour Analytics',
                'verbose_name_plural': 'Peak Hour Analytics',
                'ordering': ['-date', 'hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='ZoneAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sessions_count', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('occupancy_rate', models.FloatField(default=0)),
                ('average_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='backend_core_api.zone')),
            ],
            options={
                'verbose_name': 'Zone Analytics',
                'verbose_name_plural': 'Zone Analytics',
                'ordering': ['-date', 'zone'],
                'unique_together': {('zone', 'date')},
            },
        ),
    ]
